-- =====================================================================
-- Mfano Bora Africa Chatbot - MySQL Schema
-- Replaces the original PostgreSQL/pgvector design with a lightweight
-- MySQL 8.x schema. Retrieval is done with MySQL FULLTEXT search
-- (InnoDB) instead of a dedicated vector database, keeping the backend
-- lightweight and easy to host alongside the PHP website.
-- An optional `embedding_json` column is included so the FastAPI layer
-- can later upgrade to embedding re-ranking without a schema change.
-- =====================================================================

CREATE DATABASE IF NOT EXISTS mfano_bora_chatbot
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE mfano_bora_chatbot;

-- ---------------------------------------------------------------------
-- 1. Admin users (RBAC) - consumed by admin-php
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_users (
    user_id         INT AUTO_INCREMENT PRIMARY KEY,
    username        VARCHAR(80)  NOT NULL UNIQUE,
    email           VARCHAR(150) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    role            ENUM('superadmin','editor','viewer') NOT NULL DEFAULT 'viewer',
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at   DATETIME NULL
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 2. Knowledge base categories (Task 4: Information Classification)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kb_categories (
    category_id     INT AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE,
    description     VARCHAR(255) NULL
) ENGINE=InnoDB;

INSERT IGNORE INTO kb_categories (name, description) VALUES
 ('Company & Contact', 'Location, hours, email, general company info'),
 ('Services', 'Logistics & supply chain consultancy services'),
 ('Awards & Achievements', 'East Africa Transport, Logistics & Road Safety Awards'),
 ('Road Safety Club', 'Road Safety Club Kenya activities and membership'),
 ('Careers & Attachments', 'Industrial attachments, internships, mentoring, applications'),
 ('Blog & News', 'Latest From Our Blog content'),
 ('General FAQ', 'Miscellaneous frequently asked questions');

-- ---------------------------------------------------------------------
-- 3. Knowledge base (Task 5/6/9: KB development, organization, metadata)
--    This is the Single Source of Truth (SSOT) the FastAPI service
--    searches against, and the CSV scraper/loader populate.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS knowledge_base (
    doc_id          INT AUTO_INCREMENT PRIMARY KEY,
    category_id     INT NULL,
    question        VARCHAR(500) NULL COMMENT 'FAQ-style question, if applicable',
    content_chunk   TEXT NOT NULL COMMENT 'The answer / scraped text chunk',
    keywords        VARCHAR(500) NULL COMMENT 'Comma separated metadata keywords (Dublin Core style)',
    source_url      VARCHAR(500) NULL COMMENT 'Origin page on mfanoboraafrica.com',
    source_type     ENUM('scraped','manual','faq') NOT NULL DEFAULT 'manual',
    embedding_json  MEDIUMTEXT NULL COMMENT 'Optional pre-computed embedding vector (JSON array)',
    status          ENUM('active','draft','archived') NOT NULL DEFAULT 'active',
    last_updated    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES kb_categories(category_id) ON DELETE SET NULL,
    FULLTEXT KEY ft_kb_search (question, content_chunk, keywords)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 4. Chat sessions & logs (Task 10/16/17: retrieval design + testing)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_sessions (
    session_id      CHAR(36) PRIMARY KEY COMMENT 'UUID generated by FastAPI',
    ip_hash         VARCHAR(64) NULL COMMENT 'Hashed IP for privacy (Task 15)',
    start_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time        DATETIME NULL,
    status          ENUM('active','closed') NOT NULL DEFAULT 'active'
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS chat_logs (
    log_id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    session_id      CHAR(36) NOT NULL,
    sender_type     ENUM('user','bot') NOT NULL,
    message_text    TEXT NOT NULL,
    intent_matched  VARCHAR(150) NULL,
    doc_id_matched  INT NULL COMMENT 'FK to knowledge_base.doc_id if a KB hit was used',
    was_fallback    TINYINT(1) NOT NULL DEFAULT 0,
    timestamp       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    FOREIGN KEY (doc_id_matched) REFERENCES knowledge_base(doc_id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 5. Pre-aggregated admin KPIs (Task 17/19: evaluation + reporting)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_metrics (
    metric_id            INT AUTO_INCREMENT PRIMARY KEY,
    date_recorded         DATE NOT NULL UNIQUE,
    total_conversations   INT NOT NULL DEFAULT 0,
    total_messages        INT NOT NULL DEFAULT 0,
    fallback_rate         DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    resolution_rate        DECIMAL(5,2) NOT NULL DEFAULT 0.00
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- 6. Information gap / governance log (Task 13/14: gap analysis, governance)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kb_gap_log (
    gap_id           INT AUTO_INCREMENT PRIMARY KEY,
    unanswered_query TEXT NOT NULL,
    frequency        INT NOT NULL DEFAULT 1,
    status           ENUM('open','sourcing','resolved') NOT NULL DEFAULT 'open',
    flagged_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by      INT NULL,
    FOREIGN KEY (resolved_by) REFERENCES admin_users(user_id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- Seed a default superadmin (username: admin / password: ChangeMe!123)
-- CHANGE THIS IMMEDIATELY AFTER FIRST LOGIN.
-- ---------------------------------------------------------------------
INSERT IGNORE INTO admin_users (username, email, password_hash, role)
VALUES ('admin', 'admin@mfanoboraafrica.com',
        '$2b$10$jPQNa93EQc/1MBcaYlcbcOWWywANJQ3dqX0McN0.X1lNhKeDfmoYK',
        'superadmin');
